### ISSUE TITLE
Support for long polling

### ISSUE THREAD

**Issue by elliotchance** [iain/fake_sqs#22]
We use fake SQS on our dev environments. As part of that we have a script that acts like the elastic beanstalk worker tier that uses a 20 second long poll so we don't have to use `sleep()`'s or hit SQS constantly.

**Comment by jtmarmon** [comment]
+1

**Comment by tomwilkie** [comment]
+!

**Comment by outime** [comment]
+1

**Comment by fabregaszy** [comment]
+1

**Comment by booi** [comment]
+1

**Comment by rg1220** [comment]
+1

I would have expected it to work by adding: `ReceiveMessageWaitTimeSeconds: '10'` to the list of attributes when creating a queue. However, it didn't work. I am using [sqs-consumer](https://www.npmjs.com/package/sqs-consumer) and it's polling as fast as it possibly can since the attribute is not doing anything.

**Comment by jpbochi** [comment]
+1

perhaps we need a volunteer to make a PR?
